name: finance_treker
description: A professional finance tracking app built with Flutter.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  bloc_concurrency: ^0.2.3

  # Dependency Injection
  get_it: ^7.6.7

  # Database
  sqflite: ^2.3.2
  path: ^1.9.0

  # Charts
  fl_chart: ^0.66.2

  # SVG
  flutter_svg: ^2.0.9

  # Theme / Preferences
  shared_preferences: ^2.2.2

  # Localization
  intl: ^0.20.2

  flutter_localizations:
    sdk: flutter

  # Biometric Auth
  local_auth: ^2.1.7

  # UI Enhancements
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  go_router: ^17.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
